version: "3.1"

services:
  db:
    container_name: database
    image: sameersbn/postgresql:10-2
    environment:
      PG_PASSWORD: $DB_PASS
    restart: always
    ports:
      -5432:5432
    networks:
      -botnet
    volumes:
      - ./postgres:/var/lib/postgresql

  tgbot:
    container_name: bot
    build:
      context: .
    command: python bot.py
    restart: always
    networks:
      - botenv
    env_file:
      - ".env"
    depends_on:
      - db
    volumes:
      - .:/src


networks:
  botnet:
    driver: bridge